controller_manager:
  ros__parameters:
    update_rate: 100

    forward_velocity_controller:
      type: "forward_command_controller/ForwardCommandController"

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    imu_sensor_broadcaster:
      type: imu_sensor_broadcaster/IMUSensorBroadcaster

forward_velocity_controller:
  ros__parameters:
    joints:
      - front_left_joint
      - front_right_joint
      - back_left_joint
      - back_right_joint

    interface_name: velocity

joint_state_broadcaster:
  ros__parameters:
    use_local_topics: true

imu_sensor_broadcaster:
  ros__parameters:
    sensor_name: imu
    frame_id : imu_link
    


